
services:
  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"       # чтобы IDE/pgAdmin могли подключаться
    volumes:
      - db_dev_data:/var/lib/postgresql/data
  web:
    env_file:
      - .env.dev
    environment:
      - ENV=dev
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./:/app           # монтируем код для hot-reload
    ports:
      - "8000:8000"

volumes:
  db_dev_data:
