services:
  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"       # чтобы IDE/pgAdmin могли подключаться
    volumes:
      - db_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    env_file:
      - .env.dev
    volumes:
      - ./:/app           # монтируем код для hot-reload
      - ./mediafiles/:/app/mediafiles        # вместо external-тома
      - ./staticfiles/:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  db_dev_data:
    external: true
#  static_volume:
#    external: true
#  media_volume:
#    external: true