
services:
  db:
    image: postgres:latest
    env_file:
      - .env.prod      # для prod; в dev этот параметр переопределим
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    environment:
      - ENV=prod
    command: >
      sh -c "
        python manage.py migrate &&
        gunicorn backend.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
